permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title/
      layout: post
      assets: blog
      excerpt_separator: <!-- more -->
  -
    scope:
      path: ""
    values:
      layout: main
      assets: main

gems:
  - octopress-paginate
