title: Tyler Guillen
url: https://tylerguillen.com/blog
author: Tyler Guillen

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
paginate: 3
paginate_path: /blog/p:num/
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title/
      layout: post
      assets: blog
      excerpt_separator: <!-- more -->
  -
    scope:
      path: ""
    values:
      layout: main
      assets: main

plugins:
  - jekyll-paginate
  - jekyll-feed
